### ISSUE TITLE
Where do you put bundle install in dockerdev?

### ISSUE THREAD

**Issue by zd-project** [evilmartians/terraforming-rails#19]
New to docker and docker-compose. Trying to create a docker container for a rail application w/ sqlite database.

I followed this tutorial but commented out some advanced configs in the compose yaml file, since I'm experimenting with sqlite only and don't need any postgres/redis dependency. However, I got into an error that rails cannot be found. It looks like this: https://stackoverflow.com/questions/44098399/docker-rails-bundler-command-not-found-rails

It looked like rails were not automatically installed and the hint suggested I run `bundle install`, but if I put it into dockerfile, another error will occur, saying `Could not locate Gemfile`, which I suspect is because you didn't copy app directory into container but simply mount it into container. 

Can you explain what was your intention on not including Gemfiles into docker and how you got around with it?

Referenced docker-compose.yml:

```yaml
# Credit to
# https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development

version: '2.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: '2.6.5'
        # PG_MAJOR: '11'
        NODE_MAJOR: '10'
        YARN_VERSION: '1.19.2'
        BUNDLER_VERSION: '1.17.3'
    image: ca-policies:1.0.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      # - .dockerdev/.psqlrc:/root/.psqlrc:ro
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      # - REDIS_URL=redis://redis:6379/
      # - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
        # - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vim
        #    depends_on:
        #      postgres:
        #        condition: service_healthy
        #      redis:
        #        condition: service_healthy

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3000:3000'
      - '3002:3002'

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

    #  postgres:
    #    image: postgres:11.1
    #    volumes:
    #      - .psqlrc:/root/.psqlrc:ro
    #      - postgres:/var/lib/postgresql/data
    #      - ./log:/root/log:cached
    #    environment:
    #      - PSQL_HISTFILE=/root/log/.psql_history
    #    ports:
    #      - 5432
    #    healthcheck:
    #      test: pg_isready -U postgres -h 127.0.0.1
    #      interval: 5s

      #  redis:
      #    image: redis:3.2-alpine
      #    volumes:
      #      - redis:/data
      #    ports:
      #      - 6379
      #    healthcheck:
      #      test: redis-cli ping
      #      interval: 1s
      #      timeout: 3s
      #      retries: 30

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
```

Dockerfile:
```Dockerfile
# Credit to Vladimir Dementyev
# https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development

ARG RUBY_VERSION
# See explanation below
FROM ruby:$RUBY_VERSION-slim-buster

# ARG PG_MAJOR
ARG NODE_MAJOR
ARG BUNDLER_VERSION
ARG YARN_VERSION

# Common dependencies
RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    build-essential \
    gnupg2 \
    curl \
    less \
    git \
    sqlite3 \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

# Add NodeJS to sources list
RUN curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR.x | bash -

# Add Yarn to the sources list
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list

# Application dependencies
# We use an external Aptfile for that, stay tuned
COPY .dockerdev/Aptfile /tmp/Aptfile
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    nodejs \
    yarn=$YARN_VERSION-1 \
    $(cat /tmp/Aptfile | xargs) && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/*log

# Configure bundler
ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3

# Uncomment this line if you store Bundler settings in the project's root
# ENV BUNDLE_APP_CONFIG=.bundle

# Uncomment this line if you want to run binstubs without prefixing with `bin/` or `bundle exec`
# ENV PATH /app/bin:$PATH

# Create a directory for the app code
RUN mkdir -p /app

WORKDIR /app

# Upgrade RubyGems and install required Bundler version
RUN ls && gem update --system && \
    gem install bundler:$BUNDLER_VERSION && \
    bundler install
```
