### ISSUE TITLE
Port already in use - it seems 3000 is being used by 2 services

### ISSUE THREAD

**Issue by rmcsharry** [evilmartians/terraforming-rails#30]
Great blog post and thanks for providing the source.

But I think there is a copy-paste error?

```
services:
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3000:3000'
      - '3002:3002'

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
```

Port 3000 is being used by both the `runner` service and the `rails` service.

So when I run `docker-compose up`, this error is reported:

```
ERROR: for rails  Cannot start service rails: driver failed programming external connectivity on endpoint floorbook_rails_1 (db0834d7c3b181e127c480b2ad19832d1462e6c98d7ab2cf6584dfc2d4fb994d): Bind for 0.0.0.0:3000 failed: port is already allocated
```

https://github.com/docker/compose/issues/4950

When I change it to:

```
services:
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3002:3002'

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
```

Everything works as expected
